<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitMailTemplate
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\MailTemplate\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\MailTemplate\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\MailTemplate\\CustomEMailTemplate' => __DIR__ . '/..' . '/../lib/CustomEMailTemplate.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitMailTemplate::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitMailTemplate::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitMailTemplate::$classMap;

        }, null, ClassLoader::class);
    }
}
